Repository ahojukka5/lukuvinkkikirjasto, pull requests merged in 2021-04, with the labels that each got.

#1 Uusi ominaisuus: vinkin poistaminen
  README.md
  app/src/main/java/lukuvinkkikirjasto/dao/InMemoryTipDao.java
  app/src/main/java/lukuvinkkikirjasto/dao/JsonDao.java
  app/src/main/java/lukuvinkkikirjasto/dao/TipDao.java
  app/src/main/java/lukuvinkkikirjasto/domain/TipService.java
  app/src/main/java/lukuvinkkikirjasto/ui/ConsoleUi.java
  app/src/test/java/lukuvinkkikirjasto/dao/InMemoryTipDaoTest.java
Labels: feature, help wanted

#3 Konfiguroi checkstyle niin että pysähtyy virheeseen
  app/src/main/java/lukuvinkkikirjasto/App.java
  app/src/main/java/lukuvinkkikirjasto/dao/FilesystemProvider.java
  app/src/main/java/lukuvinkkikirjasto/dao/FilesystemWrapper.java
  app/src/main/java/lukuvinkkikirjasto/dao/InMemoryTipDao.java
  app/src/main/java/lukuvinkkikirjasto/dao/JsonDao.java
  app/src/main/java/lukuvinkkikirjasto/dao/StoredData.java
  app/src/main/java/lukuvinkkikirjasto/dao/TipDao.java
  app/src/main/java/lukuvinkkikirjasto/domain/Tip.java
  app/src/main/java/lukuvinkkikirjasto/domain/TipService.java
  app/src/main/java/lukuvinkkikirjasto/domain/matcher/All.java
  app/src/main/java/lukuvinkkikirjasto/domain/matcher/And.java
  app/src/main/java/lukuvinkkikirjasto/domain/matcher/Matcher.java
  app/src/main/java/lukuvinkkikirjasto/domain/matcher/TitleContains.java
  app/src/main/java/lukuvinkkikirjasto/ui/ConsoleUi.java
  app/src/test/java/lukuvinkkikirjasto/AppTest.java
  app/src/test/java/lukuvinkkikirjasto/RunCucumberTest.java
  app/src/test/java/lukuvinkkikirjasto/Stepdefs.java
  app/src/test/java/lukuvinkkikirjasto/dao/FilesystemWrapperTest.java
  app/src/test/java/lukuvinkkikirjasto/dao/InMemoryTipDaoTest.java
  app/src/test/java/lukuvinkkikirjasto/dao/JsonDaoTest.java
  app/src/test/java/lukuvinkkikirjasto/domain/TipServiceTest.java
  app/src/test/java/lukuvinkkikirjasto/domain/TipTest.java
  config/checkstyle/checkstyle.xml
Labels: documentation, enhancement

#13 Otsikon validointi
  README.md
  app/src/main/java/lukuvinkkikirjasto/ui/ConsoleUi.java
  app/src/test/resources/lukuvinkkikirjasto/new_tip.feature
Labels: good first issue

#11 Lisää toiminto vinkkien muokkaamiseen
  README.md
  app/src/main/java/lukuvinkkikirjasto/ui/ConsoleUi.java
  app/src/test/java/lukuvinkkikirjasto/Stepdefs.java
  app/src/test/resources/lukuvinkkikirjasto/edit_tip.feature
Labels: feature

#15 Lisää vinkki urlin perusteella (otsikoksi websivun title)
  app/build.gradle
  app/src/main/java/lukuvinkkikirjasto/domain/TipService.java
  app/src/main/java/lukuvinkkikirjasto/domain/UrlReaderProvider.java
  app/src/main/java/lukuvinkkikirjasto/domain/UrlReaderWrapper.java
  app/src/main/java/lukuvinkkikirjasto/ui/ConsoleUi.java
  app/src/test/java/lukuvinkkikirjasto/Stepdefs.java
  app/src/test/java/lukuvinkkikirjasto/domain/FakeUrlReader.java
  app/src/test/java/lukuvinkkikirjasto/domain/TipServiceTest.java
  app/src/test/resources/lukuvinkkikirjasto/add_tip_from_url.feature
Labels: feature

#12 Lisää uusia tageja lukuvinkille
  README.md
  app/src/main/java/lukuvinkkikirjasto/ui/ConsoleUi.java
  app/src/test/java/lukuvinkkikirjasto/Stepdefs.java
  app/src/test/resources/lukuvinkkikirjasto/add_tag.feature
Labels: feature
